<a href="https://colab.research.google.com/github/aiska28/Data-Maining/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Percobaan 1:

In [34]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

df = pd.read_csv('diabetes2.csv')
print(df.shape)
df.describe().transpose()

target_column = ['Outcome' ]
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

X = df [predictors ]. values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

(768, 9)
(537, 8)
(231, 8)


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1124: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[315  43]
 [ 65 114]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       358
           1       0.73      0.64      0.68       179

    accuracy                           0.80       537
   macro avg       0.78      0.76      0.77       537
weighted avg       0.79      0.80      0.80       537



/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [35]:
#Latihan (10,10,6)
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

hidden_layers = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

print("=== PERCOBAAN HIDDEN LAYER ===")

for hl in hidden_layers:
    model = MLPClassifier(
        hidden_layer_sizes=hl,
        activation='relu',
        solver='adam',
        max_iter=500,
        random_state=42
    )

    model.fit(X_train, y_train.ravel())

    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)

    print(f"Hidden Layer {hl} -> Accuracy = {acc*100:.2f}%")

=== PERCOBAAN HIDDEN LAYER ===
Hidden Layer (10, 10, 6) -> Accuracy = 74.46%
Hidden Layer (6, 8, 9) -> Accuracy = 75.76%
Hidden Layer (6, 9, 1) -> Accuracy = 74.46%


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Hidden Layer (6, 3, 9) -> Accuracy = 72.29%
Hidden Layer (7, 10, 8) -> Accuracy = 76.62%


In [36]:
#nomer 4
activations = ['identity', 'logistic', 'tanh', 'relu']

for act in activations:
    model = MLPClassifier(
        hidden_layer_sizes=(7,10,8),
        activation=act,
        solver='adam',
        max_iter=500,
        random_state=42
    )

    model.fit(X_train, y_train.ravel())
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    print(f"{act} = {acc*100:.2f}%")

identity = 74.03%
logistic = 61.47%
tanh = 75.32%
relu = 76.62%


Percobaan 2:

In [12]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standarisasi fitur
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Inisialisasi dan pelatihan model MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(2,), max_iter=5000, alpha=0.01, solver='adam', random_state=42)
mlp.fit(X_train, y_train)

# Prediksi pada data uji
y_pred = mlp.predict(X_test)

# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy * 100}%')
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Menampilkan arsitektur jaringan syaraf
print("\nArsitektur Neural Network:")
print(f"Input Layer: {X_train.shape[1]} neurons")
for i, size in enumerate(mlp.hidden_layer_sizes):
  print(f"Hidden Layer {i + 1}: {size} neurons")
print(f"Output Layer: {mlp.n_outputs_} neurons")
print(f"Fungsi Aktivasi: {mlp.activation}")

# Jika ingin melihat bobot dan bias hasil pelatihan
print("\nBobot dan Bias:")
print("Bobot antara input dan hidden layer:")
print(mlp.coefs_[0])
print("Bobot antara hidden dan output layer:")
print(mlp.coefs_[1])
print("Biase dari hidden layer:")
print(mlp.intercepts_[0])
print("Bias dari output layer:")
print(mlp.intercepts_[1])

Akurasi: 96.66666666666667%
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30


Arsitektur Neural Network:
Input Layer: 4 neurons
Hidden Layer 1: 2 neurons
Output Layer: 3 neurons
Fungsi Aktivasi: relu

Bobot dan Bias:
Bobot antara input dan hidden layer:
[[ 0.29043092  0.37942107]
 [-0.11143083 -0.92803836]
 [-0.12502741  1.30316477]
 [-0.319365    3.00535738]]
Bobot antara hidden dan output layer:
[[-0.68226519  0.66971868  0.33982245]
 [-2.13634104 -0.01405818  0.64075203]]
Biase dari hidden layer:
[-0.36447033  1.46672126]
Bias dari output layer:
[ 1.66226276 -0.12257475 -2.92008277]


Percobaan 3:

In [30]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

# Load dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

# One-hot encoding untuk label
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1, 1))

# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fungsi aktivasi sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Turunan fungsi sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Parameter jaringan neural
input_layer_neurons = X_train.shape[1]      # 4
hidden_layer_neurons = 10
output_layer_neurons = y_train.shape[1]     # 3

# Inisialisasi bobot dan bias
np.random.seed(42)

weights_input_hidden = np.random.uniform(
    size=(input_layer_neurons, hidden_layer_neurons)
)

weights_hidden_output = np.random.uniform(
    size=(hidden_layer_neurons, output_layer_neurons)
)

bias_hidden = np.random.uniform(
    size=(1, hidden_layer_neurons)
)

bias_output = np.random.uniform(
    size=(1, output_layer_neurons)
)

# Hiperparameter
learning_rate = 0.01
epochs = 5000

# Proses pelatihan
for epoch in range(epochs):

    # Forward propagation
    hidden_layer_input = (
        np.dot(X_train, weights_input_hidden)
        + bias_hidden
    )

    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = (
        np.dot(hidden_layer_output, weights_hidden_output)
        + bias_output
    )

    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    error = y_train - predicted_output

    d_predicted_output = (
        error * sigmoid_derivative(predicted_output)
    )

    error_hidden_layer = d_predicted_output.dot(
        weights_hidden_output.T
    )

    d_hidden_layer = (
        error_hidden_layer
        * sigmoid_derivative(hidden_layer_output)
    )

    # Update bobot dan bias
    weights_hidden_output += (
        hidden_layer_output.T.dot(d_predicted_output)
        * learning_rate
    )

    bias_output += (
        np.sum(d_predicted_output, axis=0, keepdims=True)
        * learning_rate
    )

    weights_input_hidden += (
        X_train.T.dot(d_hidden_layer)
        * learning_rate
    )

    bias_hidden += (
        np.sum(d_hidden_layer, axis=0, keepdims=True)
        * learning_rate
    )

    # Cetak loss setiap 1000 epoch
    if (epoch + 1) % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch + 1}, Loss: {loss}")

# Prediksi pada data uji
hidden_layer_input = (
    np.dot(X_test, weights_input_hidden)
    + bias_hidden
)

hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = (
    np.dot(hidden_layer_output, weights_hidden_output)
    + bias_output
)

predicted_output = sigmoid(output_layer_input)

# Evaluasi model
y_test_labels = np.argmax(y_test, axis=1)
predicted_labels = np.argmax(predicted_output, axis=1)

accuracy = accuracy_score(
    y_test_labels,
    predicted_labels
)

print(f"Accuracy: {accuracy * 100}%")

Epoch 1000, Loss: 0.019509750668484028
Epoch 2000, Loss: 0.013124091004250757
Epoch 3000, Loss: 0.01209906970618874
Epoch 4000, Loss: 0.011671736356642695
Epoch 5000, Loss: 0.011417050292884574
Accuracy: 96.66666666666667%


Latihan nomer **1**

In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Membaca dataset
df = pd.read_csv('Titanic-Dataset.csv')

# Menghapus kolom yang tidak digunakan
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# Mengatasi missing value
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Mengubah data kategorikal menjadi numerik
for col in ['Sex', 'Embarked']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# Menentukan fitur dan target
X = df.drop('Survived', axis=1)
y = df['Survived']

# Normalisasi data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Membagi data train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Membuat model Backpropagation
mlp = MLPClassifier(
    hidden_layer_sizes=(7,10,8),
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42
)

# Training model
mlp.fit(X_train, y_train)

# Prediksi
y_pred = mlp.predict(X_test)

# Evaluasi
print("Accuracy :", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.8134328358208955
              precision    recall  f1-score   support

           0       0.80      0.92      0.85       157
           1       0.85      0.67      0.75       111

    accuracy                           0.81       268
   macro avg       0.82      0.79      0.80       268
weighted avg       0.82      0.81      0.81       268



Latihan 2

In [44]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score

# LOAD DATASET
df = pd.read_csv("dataset_2191_sleep.csv")

print("Shape Awal :", df.shape)

# Ganti ? menjadi NaN
df = df.replace("?", np.nan)

# Ubah seluruh kolom menjadi numerik jika memungkinkan
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Tampilkan jumlah missing value
print("\nMissing Value:")
print(df.isnull().sum())

# Isi missing value dengan median
df = df.fillna(df.median(numeric_only=True))

print("\nShape Setelah Cleaning :", df.shape)

# FITUR DAN TARGET
X = df.drop("total_sleep", axis=1)
y = df["total_sleep"]

# NORMALISASI
scaler = StandardScaler()
X = scaler.fit_transform(X)

# SPLIT DATA
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

# PERCOBAAN HIDDEN LAYER
hidden_layers = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

print("\n=== PERCOBAAN HIDDEN LAYER ===")

for hl in hidden_layers:

    model = MLPRegressor(
        hidden_layer_sizes=hl,
        activation='relu',
        solver='adam',
        max_iter=5000,
        random_state=42
    )

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)

    print(f"Hidden Layer {hl} -> R2 Score = {r2:.4f}")

Shape Awal : (62, 8)

Missing Value:
body_weight             0
brain_weight            0
max_life_span           4
gestation_time          4
predation_index         0
sleep_exposure_index    0
danger_index            0
total_sleep             4
dtype: int64

Shape Setelah Cleaning : (62, 8)

=== PERCOBAAN HIDDEN LAYER ===
Hidden Layer (10, 10, 6) -> R2 Score = -1.1096
Hidden Layer (6, 8, 9) -> R2 Score = -109.7235
Hidden Layer (6, 9, 1) -> R2 Score = -11.4050
Hidden Layer (6, 3, 9) -> R2 Score = -2.7357
Hidden Layer (7, 10, 8) -> R2 Score = -8.6472


In [45]:
activations = ['identity', 'logistic', 'tanh', 'relu']

for act in activations:

    model = MLPRegressor(
        hidden_layer_sizes=(7,10,8),
        activation=act,
        max_iter=5000,
        random_state=42
    )

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    r2 = r2_score(y_test, pred)

    print(f"{act} -> R2 Score = {r2:.4f}")

identity -> R2 Score = -1.5664
logistic -> R2 Score = -0.2864
tanh -> R2 Score = -3.2166
relu -> R2 Score = -8.6472
